# Generated by Django 5.1.4 on 2025-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_date_of_birth_user_fullname_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=11, unique=True)),
                ('phone', models.CharField(max_length=1, unique=True)),
                ('code', models.SmallIntegerField()),
                ('expire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
