# Generated by Django 5.1.4 on 2025-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
