# Generated by Django 5.1.4 on 2025-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
