version: '4.37'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/public/static
      - media_volume:/app/public/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: onlineshop_db
      POSTGRES_USER: onlineshop_user
      POSTGRES_PASSWORD: abol
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/public/static
      - media_volume:/app/public/media
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
  postgres_data:
