# Generated by Django 5.1.4 on 2025-05-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_full_name_order_phone_number_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
